baseurl = "http://blog.tka.lu/"
languageCode = "zh-tw"
title = "tka's blog"
canonifyurls = true
disqusShortname = "tkalublog"

#[author]
#    name = "tka"
#
#[permalinks]
#    # Optional. Change the permalink format for the 'post' content type.
#    # The format shown here is the same one Jekyll/Octopress uses by default.
#    post = "/blog/:year/:month/:day/:title/"
#
[indexes]
    # Optional. Use if you want tags and lists.
    category = "categories"
#
##
## All parameters below here are optional and can be mixed and matched.
##
[params]
twitter   = "tkalu"
github    = "tka"
copyright = "Written by tka.lu"
analytics = "UA-21030742-4"
